# Variables
START_OVER = 'START_OVER'
WORDLIST_OVER = 'WORDLIST_OVER'
# Stages
LAYER1_ROUTES, LAYER2_ROUTES, END_ROUTES = range(3)
# Callback data
BACK, EXIT = range(2)
# layer 1
CHANNEL_SETTINGS, BOT_FUNCTIONS = range(2,4)
# layer 2
PUBLISH, STOP_CHANNEL, SHOW_LIST = range(4,7)
CHECK_RATE, SET_PROFIT = range(7,9)
# layer 3
SAVE_LONG_WORD, SAVE_SHORT_WORD, DELETE_WORD = range(9,12)
# END
END = -1